# Generated by Django 4.2.1 on 2023-05-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Type',
        ),
    ]
